<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-08 01:58
=======
# Generated by Django 4.0.3 on 2022-04-07 07:58
>>>>>>> a3f85dae08dea425b521b429146d476fdb7c1875

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
=======
            name='Comments',
>>>>>>> a3f85dae08dea425b521b429146d476fdb7c1875
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('question', models.TextField(max_length=280)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, related_name='user_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=50, null='False')),
                ('Description', models.TextField()),
                ('logical', models.BooleanField(default=True)),
                ('technical', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='query', to='helpdesk.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
<<<<<<< HEAD
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.TextField(blank=True, default='My Bio', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
=======
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.TextField(blank=True, default='My Bio', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('question', models.TextField(max_length=280)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.IntegerField(blank=True, default=True, null=True)),
                ('postslikes', models.IntegerField(blank=True, default=True, null=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.comments')),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('tag_title', models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, to='helpdesk.tag')),
                ('user', models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, related_name='user_images', to=settings.AUTH_USER_MODEL)),
>>>>>>> a3f85dae08dea425b521b429146d476fdb7c1875
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70)),
                ('user', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.post')),
            ],
        ),
    ]
