# Generated by Django 4.0.3 on 2022-04-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, to='helpdesk.tag'),
        ),
    ]
