# Generated by Django 4.0.3 on 2022-03-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
    ]
