# Generated by Django 4.0.3 on 2022-04-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_rename_date_added_comments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='helpdesk.tag'),
        ),
    ]
