# Generated by Django 4.0.3 on 2022-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_post_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='question_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_title',
            field=models.CharField(max_length=40, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='postslikes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
