# Generated by Django 4.0.3 on 2022-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='helpdesk.tag'),
        ),
    ]
