# Generated by Django 4.0.3 on 2022-04-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_like_response_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quiz',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='query', to='helpdesk.post'),
            preserve_default='False',
        ),
    ]
