# Generated by Django 4.0.3 on 2022-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, default='Uncategorized', max_length=100),
        ),
    ]
