# Generated by Django 4.0.3 on 2022-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='like', max_length=70),
        ),
    ]
