# Generated by Django 4.0.3 on 2022-04-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_like_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
    ]
