# Generated by Django 4.0.3 on 2022-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_dislike_response_alter_like_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='logical',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='technical',
        ),
        migrations.AlterField(
            model_name='dislike',
            name='response',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], max_length=70, null=True),
        ),
    ]
