# Generated by Django 4.0.3 on 2022-04-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_like_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='question_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
    ]
