# Generated by Django 4.0.3 on 2022-04-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_remove_tag_quiz_alter_like_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
    ]
