# Generated by Django 4.0.3 on 2022-04-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_remove_post_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quiz',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='query', to='helpdesk.post'),
            preserve_default='True',
        ),
    ]
