# Generated by Django 4.0.3 on 2022-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_tag_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='like', max_length=70),
        ),
    ]
