# Generated by Django 4.0.3 on 2022-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_remove_tag_logical_remove_tag_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
    ]
