# Generated by Django 4.0.3 on 2022-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_rename_comment_user_comment_user_alter_like_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
