# Generated by Django 4.0.3 on 2022-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_comment_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='Agreed'),
        ),
    ]
