# Generated by Django 4.0.3 on 2022-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_like_response_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_dislikes',
            new_name='dislikes',
        ),
        migrations.DeleteModel(
            name='Comment_like',
        ),
    ]
