# Generated by Django 4.0.3 on 2022-04-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_like_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='mydislikes',
        ),
    ]
