# Generated by Django 4.0.3 on 2022-04-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_rename_dislikes_comment_mydislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mydislikes',
            new_name='dislikes',
        ),
    ]
