# Generated by Django 4.0.3 on 2022-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_like_comment_alter_like_response_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='response',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=70, null=True),
        ),
    ]
